name: Verify App
on:
  push:
    branches:
      - main
  pull_request:

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: Prettier
        run: yarn fmt:ci
      - name: Relay Validation
        run: yarn relay:validate
      - name: ESLint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: Next.js .next/cache
        uses: actions/cache@v2.1.7
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Build
        run: yarn build
      - name: Check standalone
        run: test -f .next/standalone/package.json
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test:ci
